---
title: "ali_test_sir"
author: "Ali"
date: "15/08/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Notes on other references: (1) McMasterPandemic/notes/testing_flow.md (I am using the notation in this doc)

# On Math ans Weighting

## Model and Definitions

- Assume there are 3 groups of individuals: $S$, $I$ and $R$.
- Each group splits into 4 subgroups to incorporate the testing mechanism, so overall the model framework has 12 compartments:
$S_u,$ $S_n$, $S_p$, $S_t$, $I_u$, $I_n$, $I_p$, $I_t$, $R_u$, $R_n$, $R_p$, $R_t$.

**BMB**: yes, except that (1) two of the compartments are unnecessary (if we assume a perfectly specific test, i.e. no false positives, then $S_p$ and $S_t$ are always zero (2) we will want two 'integrator' or 'accumulator' compartments, $N$ and $P$, to collect cumulative reported neg/pos tests

## Per Capita Rate of Flow from Untested to Positive or Negative Compartments

Let's look at the flow from a particular untested compartment, $Z_i$, to a particular tested awaiting for a negative test. The equation is $$\frac{d Z_i}{dt} = - f_i Z_i,$$
 where $f_i$, is the per capita rate of flow, with the dimension of $\frac{1/time}{\#}$, where by # I mean population number.
 
1. How to define $f_i$ as a function of *testing intensity*, $t$ and *weights*, $\omega_i$.
Checkings:
- $t$ is fixed and is a parameter of the model, it is given through the reported information, dimension of $t$ is $\#/time$. (**BMB**: no, $t$ has dimensions of $1/time$)
- dimension of $\omega_i$ is $1/\#$. Possible definition of $\omega_i$:
(i) $\frac{\omega_i}{\sum_j \omega_j} \times \frac{Z_i/I_u}{\sum_j Z_j}$, where $I_u$ is untested people in compartment $I$. **BMB**: no, $\omega$ is the rate of *onward flow* from the $p$ compartment to $t$, or from $n$ back to $u$.  It has units of $1/time$.

The complicated part is the flow rate from $Z_u$ to $Z_n$, $Z_p$.  The (total, not per capita) flow from $Z_u$ to $Z_n$ is $(1-P_Z) F(W_Z) Z_u, from $Z_u$ to $Z_p$ is $P_Z F(W_Z) Z_u$.  At the simplest $F(W_Z)=W_Z$.  The flows from $Z_n$ to $Z_u$ and $Z_p$ to $Z_t$ are $\omega Z_n$ and $\omega Z_p$ respectively.