# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
# using https://github.com/r-lib/actions/tree/master/setup-pandoc
# https://github.com/marketplace/actions/ci-skip-action
on:
  workflow_dispatch

name: interactive_test

jobs:
  interactive_test:
    if: "! contains(github.event.head_commit.message, '[skip ci]')"

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - uses: actions/checkout@master
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

